window.addEventListener("DOMContentLoaded", function() {
    Game.createProtoItem("knife", "Knife", "A dull knife.", "", "weapon", "knife");
    Game.createProtoItem("cross", "Cross", "A metal-capped cross.", "resources/images/icons/items/cross01.png", "weapon", "cross01", "resources/images/textures/items/cross01.svg");
    Game.createProtoItem("alBuildingLocationKey", "Pack Street Bldg 3 Key", "A simple key to Pack Street Bldg 3", "resources/images/icons/items/key.svg", "key", "key01");
    Game.createProtoItem("pandorasBoxLocationKey", "Key to Pandora's Box", "A complex brass key meant for digitigrade mammals to Pandora's Box.", "resources/images/icons/items/pandorasBoxLocationKey.svg", "key", "key01");
    Game.createProtoItem("packstreet23StrangeNewDay", "Pack Street Chapter 23", "In the wake of Bellwether's arrest, Remmy takes stock of a changed city.", "resources/images/icons/items/packstreet23StrangeNewDay.png", "book", "bookHardcoverClosed01", "resources/images/textures/items/packStreetChapter23.svg");
    Game.createProtoItem("packstreet24PaintJob", "Pack Street Chapter 24", "Remmy finds himself doing community service.", "resources/images/icons/items/packstreet24StrangeNewDay.png", "book", "bookHardcoverClosed01", "resources/images/textures/items/packStreetChapter24.svg");
    Game.createProtoItem("theLesserKeyOfSolomon", "The Lesser Key of Solomon", "The Lesser Key of Solomon, also known as Clavicula Salomonis Regis or Lemegeton, is an anonymous grimoire on demonology. It was compiled in the mid-17th century, mostly from materials a couple of centuries older.", "resources/images/icons/items/theLesserKeyOfSolomon.png", "book", "bookHardcoverClosed01", "resources/images/textures/items/theLesserKeyOfSolomon.svg");
    Game.createProtoItem("bottle03RedSarcophagusJuice", "Red Sarcophagus Juice", "A small sample of some red liquid from the bottom of an obsidian sarcophagus.", "resources/images/icons/items/bottle03RedSarcophagusJuice.svg", "consumable", "bottle03", "resources/images/textures/items/bottle03RedSarcophagusJuice.svg");
    Game.createProtoItem("bottle04RedSarcophagusJuice", "Red Sarcophagus Juice", "A flask of some red liquid from the bottom of an obsidian sarcophagus.", "resources/images/icons/items/bottle04RedSarcophagusJuice.svg", "consumable", "bottle04", "resources/images/textures/items/bottle03RedSarcophagusJuice.svg");
    Game.createProtoItem("bottle05RedSarcophagusJuice", "Red Sarcophagus Juice", "A bottle of some red liquid from the bottom of an obsidian sarcophagus.", "resources/images/icons/items/bottle05RedSarcophagusJuice.svg", "consumable", "bottle05", "resources/images/textures/items/bottle03RedSarcophagusJuice.svg");
});