console.log("Initializing items...");
Game.createProtoItem("knife", "Knife", "A dull knife.", "knife", "knife", undefined, "weapon");
Game.createProtoItem("cross", "Cross", "A metal-capped cross.", "cross01", "cross01", "cross01", "weapon");
Game.createProtoItem("alBuildingLocationKey", "Pack Street Bldg 3 Key", "A simple key to Pack Street Bldg 3", "key", "key01", "key");
Game.createProtoItem("pandorasBoxLocationKey", "Key to Pandora's Box", "A complex brass key meant for digitigrade mammals to Pandora's Box.", "pandorasBoxLocationKey", "key01", undefined, "key");
Game.createProtoItem("packstreet23StrangeNewDay", "Pack Street Chapter 23", "In the wake of Bellwether's arrest, Remmy takes stock of a changed city.", "packstreet23StrangeNewDay", "bookHardcoverClosed01", "packStreetChapter23", "book");
Game.createProtoItem("packstreet24PaintJob", "Pack Street Chapter 24", "Remmy finds himself doing community service.", "packstreet24StrangeNewDay", "bookHardcoverClosed01", "packStreetChapter24", "book");
Game.createProtoItem("theLesserKeyOfSolomon", "The Lesser Key of Solomon", "The Lesser Key of Solomon, also known as Clavicula Salomonis Regis or Lemegeton, is an anonymous grimoire on demonology. It was compiled in the mid-17th century, mostly from materials a couple of centuries older.", "theLesserKeyOfSolomon", "bookHardcoverClosed01", "theLesserKeyOfSolomon", "book");
Game.createProtoItem("bottle03RedSarcophagusJuice", "Red Sarcophagus Juice", "A small sample of some red liquid from the bottom of an obsidian sarcophagus.", "bottle03RedSarcophagusJuice", "bottle03", "bottle03RedSarcophagusJuice", "consumable");
Game.createProtoItem("bottle04RedSarcophagusJuice", "Red Sarcophagus Juice", "A flask of some red liquid from the bottom of an obsidian sarcophagus.", "bottle04RedSarcophagusJuice", "bottle04", "bottle03RedSarcophagusJuice", "consumable");
Game.createProtoItem("bottle05RedSarcophagusJuice", "Red Sarcophagus Juice", "A bottle of some red liquid from the bottom of an obsidian sarcophagus.", "bottle05RedSarcophagusJuice", "bottle05", "bottle03RedSarcophagusJuice", "consumable");
Game.createProtoItem("mountainChocolateWrapper", "Giant Toblerone", "A giant, delicious toblerone! You don't deserve it, though.", "mountainChocolate01", "mountainChocolateWrapper01", "vChocolateV", "consumable");
Game.createProtoItem("mountainChocolateBar", "Giant Toblerone", "A giant, delicious toblerone! You don't deserve it, though.", "mountainChocolate01", "mountainChocolateBar01", "vChocolateV", "consumable");
Game.createProtoItem("woodenMallet", "Wooden Mallet", "A mallet made from unrefined wood.", undefined, "mallet", "woodenMallet", "weapon");
Game.createProtoItem("birdMask", "Bird Mask", "A mask resembling a bird's beak.", "birdMask01", "birdMask01", undefined, "clothing");
Game.createProtoItem("morningstar", "Morningstar", "A spiked mace.", "morningstar", "morningstar", undefined, "weapon");
Game.createProtoItem("cudgel", "Cudgel", "A chunk of metal attached to a stick.", "cudgel", "cudgel", undefined, "weapon");
Game.createProtoItem("warhammer01", "Warhammer", "A dangerous looking, spiked hammer.", "warhammer01", "warhammer01", undefined, "weapon");
Game.createProtoItem("wizardHat02", "Wizard Hat", "A silly, wide-brimmed hat.", "wizardHat02", "wizardHat02", undefined, "weapon");
Game.createProtoItem("shortsword", "Short Sword", "A simple short sword.", "shortsword", "shortsword", undefined, "weapon");
Game.createProtoItem("sword", "Sword", "A simple sword.", "sword", "sword", undefined, "weapon");

