class CharacterStatsGUI {
    static initialize() {
        CharacterStatsGUI.initialized = false;
        CharacterStatsGUI.controller = null;
        CharacterStatsGUI.nameField = null;
        CharacterStatsGUI.generateController();
        return 0;
    }
    static resize() {
        if (CharacterStatsGUI.initialized != true) {
            return 1;
        }
        CharacterStatsGUI.controller.height = String(Math.max(Game.engine.getRenderHeight(), GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.controller.width = String(Math.max(Game.engine.getRenderWidth(), GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.header.height = String(Math.max(GameGUI.fontSizeInPixelsWithSpacing * 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.header.width = CharacterStatsGUI.controller.width;
        CharacterStatsGUI.nameContainer.height = CharacterStatsGUI.header.height;
        CharacterStatsGUI.nameContainer.width = String(Math.max(CharacterStatsGUI.header.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.nameField.height = String(Math.max((CharacterStatsGUI.nameContainer.heightInPixels / 3) * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.nameField.width = String(CharacterStatsGUI.nameContainer.widthInPixels - GameGUI.fontSizeSpacing).concat("px");
        CharacterStatsGUI.nameField.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.nameLabel.height = String(Math.max(CharacterStatsGUI.nameContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.nameLabel.width = CharacterStatsGUI.nameContainer.width;
        CharacterStatsGUI.nameLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.infoContainer.height = CharacterStatsGUI.header.height;
        CharacterStatsGUI.infoContainer.width = String(Math.max((CharacterStatsGUI.header.widthInPixels / 3) * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.infoTop.height = String(Math.max(CharacterStatsGUI.infoContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.infoTop.width = CharacterStatsGUI.infoContainer.width;
        CharacterStatsGUI.classContainer.height = CharacterStatsGUI.infoTop.height;
        CharacterStatsGUI.classContainer.width = String(Math.max(CharacterStatsGUI.infoTop.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.classField.height = String(Math.max((CharacterStatsGUI.classContainer.heightInPixels / 3) * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.classField.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.classLabel.height = String(Math.max(CharacterStatsGUI.classContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.classLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.backgroundContainer.height = CharacterStatsGUI.infoTop.height;
        CharacterStatsGUI.backgroundContainer.width = String(Math.max(CharacterStatsGUI.infoTop.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.backgroundField.height = String(Math.max((CharacterStatsGUI.backgroundContainer.heightInPixels / 3) * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.backgroundField.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.backgroundLabel.height = String(Math.max(CharacterStatsGUI.backgroundContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.backgroundLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.accountContainer.height = CharacterStatsGUI.infoTop.height;
        CharacterStatsGUI.accountContainer.width = String(Math.max(CharacterStatsGUI.infoTop.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.accountField.height = String(Math.max((CharacterStatsGUI.accountContainer.heightInPixels / 3) * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.accountField.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.accountLabel.height = String(Math.max(CharacterStatsGUI.accountContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.accountLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.infoBottom.height = String(Math.max(CharacterStatsGUI.infoContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.infoBottom.width = CharacterStatsGUI.infoContainer.width;
        CharacterStatsGUI.raceContainer.height = CharacterStatsGUI.infoBottom.height;
        CharacterStatsGUI.raceContainer.width = String(Math.max(CharacterStatsGUI.infoBottom.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.raceField.height = String(Math.max((CharacterStatsGUI.raceContainer.heightInPixels / 3) * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.raceField.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.raceLabel.height = String(Math.max(CharacterStatsGUI.raceContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.raceLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.alignmentContainer.height = CharacterStatsGUI.infoBottom.height;
        CharacterStatsGUI.alignmentContainer.width = String(Math.max(CharacterStatsGUI.infoBottom.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.alignmentField.height = String(Math.max((CharacterStatsGUI.alignmentContainer.heightInPixels / 3) * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.alignmentField.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.alignmentLabel.height = String(Math.max(CharacterStatsGUI.alignmentContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.alignmentLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.xpContainer.height = CharacterStatsGUI.infoBottom.height;
        CharacterStatsGUI.xpContainer.width = String(Math.max(CharacterStatsGUI.infoBottom.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.xpField.height = String(Math.max((CharacterStatsGUI.xpContainer.heightInPixels / 3) * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.xpField.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.xpLabel.height = String(Math.max(CharacterStatsGUI.xpContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.xpLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.body.height = String(Math.max(CharacterStatsGUI.controller.heightInPixels - (GameGUI.fontSizeInPixelsWithSpacing * 3), GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.body.width = CharacterStatsGUI.controller.width;
        CharacterStatsGUI.colA.height = CharacterStatsGUI.body.height;
        CharacterStatsGUI.colA.width = String(Math.max(CharacterStatsGUI.body.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.colARowA.height = String(Math.max((CharacterStatsGUI.colA.heightInPixels / 7) * 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.colARowA.width = CharacterStatsGUI.colA.width;
        CharacterStatsGUI.colARowAColA.height = CharacterStatsGUI.colARowA.height;
        CharacterStatsGUI.colARowAColA.width = String(Math.max(CharacterStatsGUI.colARowA.widthInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.strengthContainer.height = String(Math.max(CharacterStatsGUI.colARowAColA.heightInPixels / 6, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.strengthContainer.width = CharacterStatsGUI.colARowAColA.width;
        CharacterStatsGUI.strengthButtons.height = CharacterStatsGUI.strengthContainer.height;
        CharacterStatsGUI.strengthButtons.width = String(Math.max(CharacterStatsGUI.strengthContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.strengthIncButton.height = String(Math.max(CharacterStatsGUI.strengthButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.strengthIncButton.width = CharacterStatsGUI.strengthButtons.width;
        CharacterStatsGUI.strengthIncButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.strengthDecButton.height = String(Math.max(CharacterStatsGUI.strengthButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.strengthDecButton.width = CharacterStatsGUI.strengthButtons.width;
        CharacterStatsGUI.strengthDecButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.strengthData.height = CharacterStatsGUI.strengthContainer.height;
        CharacterStatsGUI.strengthData.width = String(Math.max(CharacterStatsGUI.strengthContainer.widthInPixels - CharacterStatsGUI.strengthButtons.widthInPixels, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.strengthLabel.height = String(Math.max(CharacterStatsGUI.strengthContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.strengthLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.strengthAbilityModifier.height = String(Math.max(CharacterStatsGUI.strengthContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.strengthAbilityModifier.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.strengthAbilityField.height = String(Math.max(CharacterStatsGUI.strengthContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.strengthAbilityField.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.dexterityContainer.height = String(Math.max(CharacterStatsGUI.colARowAColA.heightInPixels / 6, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.dexterityContainer.width = CharacterStatsGUI.colARowAColA.width;
        CharacterStatsGUI.dexterityButtons.height = CharacterStatsGUI.dexterityContainer.height;
        CharacterStatsGUI.dexterityButtons.width = String(Math.max(CharacterStatsGUI.dexterityContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.dexterityIncButton.height = String(Math.max(CharacterStatsGUI.dexterityButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.dexterityIncButton.width = CharacterStatsGUI.dexterityButtons.width;
        CharacterStatsGUI.dexterityIncButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.dexterityDecButton.height = String(Math.max(CharacterStatsGUI.dexterityButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.dexterityDecButton.width = CharacterStatsGUI.dexterityButtons.width;
        CharacterStatsGUI.dexterityDecButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.dexterityData.height = CharacterStatsGUI.dexterityContainer.height;
        CharacterStatsGUI.dexterityData.width = String(Math.max(CharacterStatsGUI.dexterityContainer.widthInPixels - CharacterStatsGUI.dexterityButtons.widthInPixels, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.dexterityLabel.height = String(Math.max(CharacterStatsGUI.dexterityContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.dexterityLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.dexterityAbilityModifier.height = String(Math.max(CharacterStatsGUI.dexterityContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.dexterityAbilityModifier.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.dexterityAbilityField.height = String(Math.max(CharacterStatsGUI.dexterityContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.dexterityAbilityField.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.constitutionContainer.height = String(Math.max(CharacterStatsGUI.colARowAColA.heightInPixels / 6, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.constitutionContainer.width = CharacterStatsGUI.colARowAColA.width;
        CharacterStatsGUI.constitutionButtons.height = CharacterStatsGUI.constitutionContainer.height;
        CharacterStatsGUI.constitutionButtons.width = String(Math.max(CharacterStatsGUI.constitutionContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.constitutionIncButton.height = String(Math.max(CharacterStatsGUI.constitutionButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.constitutionIncButton.width = CharacterStatsGUI.constitutionButtons.width;
        CharacterStatsGUI.constitutionIncButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.constitutionDecButton.height = String(Math.max(CharacterStatsGUI.constitutionButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.constitutionDecButton.width = CharacterStatsGUI.constitutionButtons.width;
        CharacterStatsGUI.constitutionDecButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.constitutionData.height = CharacterStatsGUI.constitutionContainer.height;
        CharacterStatsGUI.constitutionData.width = String(Math.max(CharacterStatsGUI.constitutionContainer.widthInPixels - CharacterStatsGUI.constitutionButtons.widthInPixels, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.constitutionLabel.height = String(Math.max(CharacterStatsGUI.constitutionContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.constitutionLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.constitutionAbilityModifier.height = String(Math.max(CharacterStatsGUI.constitutionContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.constitutionAbilityModifier.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.constitutionAbilityField.height = String(Math.max(CharacterStatsGUI.constitutionContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.constitutionAbilityField.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.intelligenceContainer.height = String(Math.max(CharacterStatsGUI.colARowAColA.heightInPixels / 6, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.intelligenceContainer.width = CharacterStatsGUI.colARowAColA.width;
        CharacterStatsGUI.intelligenceButtons.height = CharacterStatsGUI.intelligenceContainer.height;
        CharacterStatsGUI.intelligenceButtons.width = String(Math.max(CharacterStatsGUI.intelligenceContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.intelligenceIncButton.height = String(Math.max(CharacterStatsGUI.intelligenceButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.intelligenceIncButton.width = CharacterStatsGUI.intelligenceButtons.width;
        CharacterStatsGUI.intelligenceIncButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.intelligenceDecButton.height = String(Math.max(CharacterStatsGUI.intelligenceButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.intelligenceDecButton.width = CharacterStatsGUI.intelligenceButtons.width;
        CharacterStatsGUI.intelligenceDecButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.intelligenceData.height = CharacterStatsGUI.intelligenceContainer.height;
        CharacterStatsGUI.intelligenceData.width = String(Math.max(CharacterStatsGUI.intelligenceContainer.widthInPixels - CharacterStatsGUI.intelligenceButtons.widthInPixels, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.intelligenceLabel.height = String(Math.max(CharacterStatsGUI.intelligenceContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.intelligenceLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.intelligenceAbilityModifier.height = String(Math.max(CharacterStatsGUI.intelligenceContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.intelligenceAbilityModifier.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.intelligenceAbilityField.height = String(Math.max(CharacterStatsGUI.intelligenceContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.intelligenceAbilityField.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.wisdomContainer.height = String(Math.max(CharacterStatsGUI.colARowAColA.heightInPixels / 6, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.wisdomContainer.width = CharacterStatsGUI.colARowAColA.width;
        CharacterStatsGUI.wisdomButtons.height = CharacterStatsGUI.wisdomContainer.height;
        CharacterStatsGUI.wisdomButtons.width = String(Math.max(CharacterStatsGUI.wisdomContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.wisdomIncButton.height = String(Math.max(CharacterStatsGUI.wisdomButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.wisdomIncButton.width = CharacterStatsGUI.wisdomButtons.width;
        CharacterStatsGUI.wisdomIncButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.wisdomDecButton.height = String(Math.max(CharacterStatsGUI.wisdomButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.wisdomDecButton.width = CharacterStatsGUI.wisdomButtons.width;
        CharacterStatsGUI.wisdomDecButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.wisdomData.height = CharacterStatsGUI.wisdomContainer.height;
        CharacterStatsGUI.wisdomData.width = String(Math.max(CharacterStatsGUI.wisdomContainer.widthInPixels - CharacterStatsGUI.wisdomButtons.widthInPixels, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.wisdomLabel.height = String(Math.max(CharacterStatsGUI.wisdomContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.wisdomLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.wisdomAbilityModifier.height = String(Math.max(CharacterStatsGUI.wisdomContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.wisdomAbilityModifier.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.wisdomAbilityField.height = String(Math.max(CharacterStatsGUI.wisdomContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.wisdomAbilityField.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.charismaContainer.height = String(Math.max(CharacterStatsGUI.colARowAColA.heightInPixels / 6, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.charismaContainer.width = CharacterStatsGUI.colARowAColA.width;
        CharacterStatsGUI.charismaButtons.height = CharacterStatsGUI.charismaContainer.height;
        CharacterStatsGUI.charismaButtons.width = String(Math.max(CharacterStatsGUI.charismaContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.charismaIncButton.height = String(Math.max(CharacterStatsGUI.charismaButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.charismaIncButton.width = CharacterStatsGUI.charismaButtons.width;
        CharacterStatsGUI.charismaIncButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.charismaDecButton.height = String(Math.max(CharacterStatsGUI.charismaButtons.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.charismaDecButton.width = CharacterStatsGUI.charismaButtons.width;
        CharacterStatsGUI.charismaDecButton.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.charismaData.height = CharacterStatsGUI.charismaContainer.height;
        CharacterStatsGUI.charismaData.width = String(Math.max(CharacterStatsGUI.charismaContainer.widthInPixels - CharacterStatsGUI.charismaButtons.widthInPixels, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.charismaLabel.height = String(Math.max(CharacterStatsGUI.charismaContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.charismaLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.charismaAbilityModifier.height = String(Math.max(CharacterStatsGUI.charismaContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.charismaAbilityModifier.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.charismaAbilityField.height = String(Math.max(CharacterStatsGUI.charismaContainer.heightInPixels / 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.charismaAbilityField.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.colARowAColB.height = CharacterStatsGUI.colARowA.height;
        CharacterStatsGUI.colARowAColB.width = String(Math.max(CharacterStatsGUI.colARowA.widthInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.inspirationContainer.height = String(Math.max(CharacterStatsGUI.colARowAColB.heightInPixels / 12, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.inspirationContainer.width = CharacterStatsGUI.colARowAColB.width;
        CharacterStatsGUI.inspirationField.height = CharacterStatsGUI.inspirationContainer.height;
        CharacterStatsGUI.inspirationField.width = CharacterStatsGUI.inspirationField.height;
        CharacterStatsGUI.inspirationField.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.inspirationLabel.height = CharacterStatsGUI.inspirationContainer.height;
        CharacterStatsGUI.inspirationLabel.width = String(Math.max(CharacterStatsGUI.inspirationContainer.widthInPixels - CharacterStatsGUI.inspirationField.widthInPixels, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.inspirationLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.proficiencyBonusContainer.height = String(Math.max(CharacterStatsGUI.colARowAColB.heightInPixels / 12, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.proficiencyBonusContainer.width = CharacterStatsGUI.colARowAColB.width;
        CharacterStatsGUI.proficiencyBonusField.height = CharacterStatsGUI.proficiencyBonusContainer.height;
        CharacterStatsGUI.proficiencyBonusField.width = CharacterStatsGUI.proficiencyBonusField.height;
        CharacterStatsGUI.proficiencyBonusField.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.proficiencyBonusLabel.height = CharacterStatsGUI.proficiencyBonusContainer.height;
        CharacterStatsGUI.proficiencyBonusLabel.width = String(Math.max(CharacterStatsGUI.proficiencyBonusContainer.widthInPixels - CharacterStatsGUI.proficiencyBonusField.widthInPixels, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.proficiencyBonusLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.colARowB.height = String(Math.max((CharacterStatsGUI.colA.heightInPixels / 7) * 0.5, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.colARowB.width = CharacterStatsGUI.colA.width;
        CharacterStatsGUI.passiveWisdomField.height = CharacterStatsGUI.colARowB.height;
        CharacterStatsGUI.passiveWisdomField.width = CharacterStatsGUI.passiveWisdomField.height;
        CharacterStatsGUI.passiveWisdomField.fontSize = GameGUI.fontSize;
        CharacterStatsGUI.passiveWisdomLabel.height = CharacterStatsGUI.colARowB.height;
        CharacterStatsGUI.passiveWisdomLabel.width = String(Math.max(CharacterStatsGUI.colARowB.widthInPixels - CharacterStatsGUI.passiveWisdomField.widthInPixels, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.passiveWisdomLabel.fontSize = GameGUI.fontSizeSmall;
        CharacterStatsGUI.colARowC.height = String(Math.max((CharacterStatsGUI.colA.heightInPixels / 7) * 2.5, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.colARowC.width = CharacterStatsGUI.colA.width;
        CharacterStatsGUI.colB.height = CharacterStatsGUI.body.height;
        CharacterStatsGUI.colB.width = String(Math.max(CharacterStatsGUI.body.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        CharacterStatsGUI.colC.height = CharacterStatsGUI.body.height;
        CharacterStatsGUI.colC.width = String(Math.max(CharacterStatsGUI.body.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
        return 0;
    }
    static generateController() {
        let controller = new BABYLON.GUI.StackPanel("stats");
            controller.height = String(Game.engine.getRenderHeight()).concat("px");
            controller.width = String(Game.engine.getRenderWidth()).concat("px");
            controller.isVertical = true;
            controller.background = GameGUI.background;
            let header = new BABYLON.GUI.StackPanel("header");
                header.height = String(GameGUI.fontSizeInPixelsWithSpacing * 4).concat("px");
                header.width = controller.width;
                header.isVertical = false;
                let hNameContainer = new BABYLON.GUI.StackPanel("nameContainer");
                    hNameContainer.height = header.height;
                    hNameContainer.width = String(Math.max(header.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                    let hNCField = new BABYLON.GUI.InputText("nameField");
                        hNCField.height = String(Math.max(hNameContainer.heightInPixels / 3 * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                        hNCField.width = String(hNameContainer.widthInPixels - GameGUI.fontSizeSpacing).concat("px");
                        hNCField.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                        hNCField.color = GameGUI.color;
                        hNCField.fontSize = GameGUI.fontSize;
                    hNameContainer.addControl(hNCField);
                    let hNCLabel = new BABYLON.GUI.TextBlock("nameLabel");
                        hNCLabel.height = String(Math.max(hNameContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                        hNCLabel.width = hNameContainer.width;
                        hNCLabel.text = "Character Name";
                        hNCLabel.color = GameGUI.color;
                        hNCLabel.fontSize = GameGUI.fontSizeSmall;
                        hNCLabel.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                    hNameContainer.addControl(hNCLabel);
                header.addControl(hNameContainer);
                let hInfoContainer = new BABYLON.GUI.StackPanel("infoContainer");
                    hInfoContainer.height = header.height;
                    hInfoContainer.width = String(Math.max(header.widthInPixels / 3 * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                    hInfoContainer.isVertical = true;
                    let hICTop = new BABYLON.GUI.StackPanel("infoContainerTop");
                        hICTop.height = String(Math.max(hInfoContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                        hICTop.width = hInfoContainer.width;
                        hICTop.isVertical = false;
                        let hICTClassContainer = new BABYLON.GUI.StackPanel("classContainer");
                            hICTClassContainer.height = hICTop.height;
                            hICTClassContainer.width = String(Math.max(hICTop.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                            hICTClassContainer.isVertical = true;
                            let hICTCCText = new BABYLON.GUI.TextBlock("className");
                                hICTCCText.height = String(Math.max(hICTClassContainer.heightInPixels / 3 * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICTCCText.color = GameGUI.color;
                                hICTCCText.fontSize = GameGUI.fontSize;
                                hICTCCText.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICTClassContainer.addControl(hICTCCText);
                            let hICTCCLabel = new BABYLON.GUI.TextBlock("classLabel");
                                hICTCCLabel.height = String(Math.max(hICTClassContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICTCCLabel.text = "Class & Level";
                                hICTCCLabel.color = GameGUI.color;
                                hICTCCLabel.fontSize = GameGUI.fontSizeSmall;
                                hICTCCLabel.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICTClassContainer.addControl(hICTCCLabel);
                        hICTop.addControl(hICTClassContainer);
                        let hICTBGgContainer = new BABYLON.GUI.StackPanel("backgroundContainer");
                            hICTBGgContainer.height = hICTop.height;
                            hICTBGgContainer.width = String(Math.max(hICTop.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                            hICTBGgContainer.isVertical = true;
                            let hICTBGCText = new BABYLON.GUI.TextBlock("bgName");
                                hICTBGCText.height = String(Math.max(hICTBGgContainer.heightInPixels / 3 * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICTBGCText.color = GameGUI.color;
                                hICTBGCText.fontSize = GameGUI.fontSize;
                                hICTBGCText.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICTBGgContainer.addControl(hICTBGCText);
                            let hICTBGCLabel = new BABYLON.GUI.TextBlock("bgLabel");
                                hICTBGCLabel.height = String(Math.max(hICTBGgContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICTBGCLabel.text = "Background";
                                hICTBGCLabel.color = GameGUI.color;
                                hICTBGCLabel.fontSize = GameGUI.fontSizeSmall;
                                hICTBGCLabel.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICTBGgContainer.addControl(hICTBGCLabel);
                        hICTop.addControl(hICTBGgContainer);
                        let hICTAccNameContainer = new BABYLON.GUI.StackPanel("accountNameContainer");
                            hICTAccNameContainer.height = hICTop.height;
                            hICTAccNameContainer.width = String(Math.max(hICTop.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                            hICTAccNameContainer.isVertical = true;
                            let hICTANCText = new BABYLON.GUI.TextBlock("anName");
                                hICTANCText.height = String(Math.max(hICTAccNameContainer.heightInPixels / 3 * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICTANCText.color = GameGUI.color;
                                hICTANCText.fontSize = GameGUI.fontSize;
                                hICTANCText.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICTAccNameContainer.addControl(hICTANCText);
                            let hICTANCLabel = new BABYLON.GUI.TextBlock("anLabel");
                                hICTANCLabel.height = String(Math.max(hICTAccNameContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICTANCLabel.text = "Account Name";
                                hICTANCLabel.color = GameGUI.color;
                                hICTANCLabel.fontSize = GameGUI.fontSizeSmall;
                                hICTANCLabel.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICTAccNameContainer.addControl(hICTANCLabel);
                        hICTop.addControl(hICTAccNameContainer);
                    hInfoContainer.addControl(hICTop);
                    let hICBot = new BABYLON.GUI.StackPanel("infoSubContainerBottom");
                        hICBot.height = String(Math.max(hInfoContainer.heightInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                        hICBot.width = hInfoContainer.width;
                        hICBot.isVertical = false;
                        hInfoContainer.addControl(hICBot);
                        let hICBRaceContainer = new BABYLON.GUI.StackPanel("infoRaceContainer");
                            hICBRaceContainer.height = hICBot.height;
                            hICBRaceContainer.width = String(Math.max(hICBot.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                            hICBRaceContainer.isVertical = true;
                            let hICBRCText = new BABYLON.GUI.TextBlock("raceName");
                                hICBRCText.height = String(Math.max(hICBRaceContainer.heightInPixels / 3 * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICBRCText.color = GameGUI.color;
                                hICBRCText.fontSize = GameGUI.fontSize;
                                hICBRCText.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICBRaceContainer.addControl(hICBRCText);
                            let hICBRCLabel = new BABYLON.GUI.TextBlock("raceLabel");
                                hICBRCLabel.height = String(Math.max(hICBRaceContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICBRCLabel.text = "Race";
                                hICBRCLabel.color = GameGUI.color;
                                hICBRCLabel.fontSize = GameGUI.fontSizeSmall;
                                hICBRCLabel.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICBRaceContainer.addControl(hICBRCLabel);
                        hICBot.addControl(hICBRaceContainer);
                        let hICBAlignmentContainer = new BABYLON.GUI.StackPanel("alignmentContainer");
                            hICBAlignmentContainer.height = hICBot.height;
                            hICBAlignmentContainer.width = String(Math.max(hICBot.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                            hICBAlignmentContainer.isVertical = true;
                            let hICBACText = new BABYLON.GUI.TextBlock("alignmentName");
                                hICBACText.height = String(Math.max(hICBAlignmentContainer.heightInPixels / 3 * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICBACText.color = GameGUI.color;
                                hICBACText.fontSize = GameGUI.fontSize;
                                hICBACText.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICBAlignmentContainer.addControl(hICBACText);
                            let hICBACLabel = new BABYLON.GUI.TextBlock("alignmentLabel");
                                hICBACLabel.height = String(Math.max(hICBAlignmentContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICBACLabel.text = "Alignment";
                                hICBACLabel.color = GameGUI.color;
                                hICBACLabel.fontSize = GameGUI.fontSizeSmall;
                                hICBACLabel.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICBAlignmentContainer.addControl(hICBACLabel);
                        hICBot.addControl(hICBAlignmentContainer);
                        let hICBXPContainer = new BABYLON.GUI.StackPanel("xpContainer");
                            hICBXPContainer.height = hICBot.height;
                            hICBXPContainer.width = String(Math.max(hICBot.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                            hICBXPContainer.isVertical = true;
                            let hICBXPCText = new BABYLON.GUI.TextBlock("xpName");
                                hICBXPCText.height = String(Math.max(hICBXPContainer.heightInPixels / 3 * 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICBXPCText.color = GameGUI.color;
                                hICBXPCText.fontSize = GameGUI.fontSize;
                                hICBXPCText.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICBXPContainer.addControl(hICBXPCText);
                            let hICBXPCLabel = new BABYLON.GUI.TextBlock("xpLabel");
                                hICBXPCLabel.height = String(Math.max(hICBXPContainer.heightInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                                hICBXPCLabel.text = "Experience Points";
                                hICBXPCLabel.color = GameGUI.color;
                                hICBXPCLabel.fontSize = GameGUI.fontSizeSmall;
                                hICBXPCLabel.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_LEFT;
                            hICBXPContainer.addControl(hICBXPCLabel);
                        hICBot.addControl(hICBXPContainer);
                header.addControl(hInfoContainer);
            controller.addControl(header);
            let body = new BABYLON.GUI.StackPanel("body");
                body.height = String(Math.max(controller.heightInPixels - (GameGUI.fontSizeInPixelsWithSpacing * 3), GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                body.width = controller.width;
                body.isVertical = false;
                let colA = new BABYLON.GUI.StackPanel("colA");
                    colA.height = body.height;
                    colA.width = String(Math.max(body.widthInPixels / 3, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                    colA.isVertical = true;
                    let colARowA = new BABYLON.GUI.StackPanel("colARowA");
                        colARowA.height = String(Math.max(colA.heightInPixels / 7 * 4, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                        colARowA.width = colA.width;
                        colARowA.isVertical = false;
                        let colARowAColA = new BABYLON.GUI.StackPanel("colARowAColA");
                            colARowAColA.height = colARowA.height;
                            colARowAColA.width = String(Math.max(colARowA.widthInPixels / 2, GameGUI.fontSizeInPixelsWithSpacing)).concat("px");
                            colARowAColA.isVertical = true;
                            let strengthContainer = new BABYLON.GUI.StackPanel("strengthContainer");
                                strengthContainer.height = String(colARowAColA.heightInPixels / 6).concat("px");
                                strengthContainer.width = colARowAColA.width;
                                strengthContainer.isVertical = false;
                                let strengthButtons = new BABYLON.GUI.StackPanel("strengthButtons");
                                    strengthButtons.height = strengthContainer.height;
                                    strengthButtons.width = String(strengthContainer.heightInPixels / 2).concat("px");
                                    strengthButtons.isVeritcal = true;
                                    let strengthIncButton = BABYLON.GUI.Button.CreateImageButton("strengthInc", "+");
                                        strengthIncButton.height = String(strengthButtons.heightInPixels / 2).concat("px");
                                        strengthIncButton.width = strengthButtons.width;
                                        strengthIncButton.fontSize = GameGUI.fontSize;
                                        strengthIncButton.color = GameGUI.color;
                                        strengthIncButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        strengthIncButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        strengthIncButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        strengthIncButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    strengthButtons.addControl(strengthIncButton);
                                    let strengthDecButton = BABYLON.GUI.Button.CreateImageButton("strengthDec", "-");
                                        strengthDecButton.height = String(strengthButtons.heightInPixels / 2).concat("px");
                                        strengthDecButton.width = strengthButtons.width;
                                        strengthDecButton.fontSize = GameGUI.fontSize;
                                        strengthDecButton.color = GameGUI.color;
                                        strengthDecButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        strengthDecButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        strengthDecButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        strengthDecButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    strengthButtons.addControl(strengthDecButton);
                                strengthContainer.addControl(strengthButtons);
                                let strengthData = new BABYLON.GUI.StackPanel("strengthData");
                                    strengthData.height = strengthContainer.height;
                                    strengthData.width = String(strengthContainer.widthInPixels - strengthButtons.widthInPixels).concat("px");
                                    strengthData.isVertical = true;
                                    let strengthLabel = new BABYLON.GUI.TextBlock("strengthLabel");
                                        strengthLabel.height = String(strengthContainer.heightInPixels / 4).concat("px");
                                        strengthLabel.fontSize = GameGUI.fontSizeSmall;
                                        strengthLabel.text = "Strength";
                                        strengthLabel.color = GameGUI.color;
                                    strengthData.addControl(strengthLabel);
                                    let strengthAbilityModifier = new BABYLON.GUI.TextBlock("strengthAbilityModifier");
                                        strengthAbilityModifier.height = String(strengthContainer.heightInPixels / 2).concat("px");
                                        strengthAbilityModifier.fontSize = GameGUI.fontSize;
                                        strengthAbilityModifier.text = "0";
                                        strengthAbilityModifier.color = GameGUI.color;
                                    strengthData.addControl(strengthAbilityModifier);
                                    let strengthAbilityScore = new BABYLON.GUI.InputText("strengthAbilityScore");
                                        strengthAbilityScore.height = String(strengthContainer.heightInPixels / 4).concat("px");
                                        strengthAbilityScore.fontSize = GameGUI.fontSizeSmall;
                                        strengthAbilityScore.text = "10";
                                        strengthAbilityScore.color = GameGUI.color;
                                        strengthAbilityScore.thickness = 0;
                                        strengthAbilityScore.background = "";
                                        strengthAbilityScore.isEnabled = false;
                                    strengthData.addControl(strengthAbilityScore);
                                strengthContainer.addControl(strengthData);
                            colARowAColA.addControl(strengthContainer);
                            let dexterityContainer = new BABYLON.GUI.StackPanel("dexterityContainer");
                                dexterityContainer.height = String(colARowAColA.heightInPixels / 6).concat("px");
                                dexterityContainer.width = colARowAColA.width;
                                dexterityContainer.isVertical = false;
                                let dexterityButtons = new BABYLON.GUI.StackPanel("dexterityButtons");
                                    dexterityButtons.height = dexterityContainer.height;
                                    dexterityButtons.width = String(dexterityContainer.heightInPixels / 2).concat("px");
                                    dexterityButtons.isVeritcal = true;
                                    let dexterityIncButton = BABYLON.GUI.Button.CreateImageButton("dexterityInc", "+");
                                        dexterityIncButton.height = String(dexterityButtons.heightInPixels / 2).concat("px");
                                        dexterityIncButton.width = dexterityButtons.width;
                                        dexterityIncButton.fontSize = GameGUI.fontSize;
                                        dexterityIncButton.color = GameGUI.color;
                                        dexterityIncButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        dexterityIncButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        dexterityIncButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        dexterityIncButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    dexterityButtons.addControl(dexterityIncButton);
                                    let dexterityDecButton = BABYLON.GUI.Button.CreateImageButton("dexterityDec", "-");
                                        dexterityDecButton.height = String(dexterityButtons.heightInPixels / 2).concat("px");
                                        dexterityDecButton.width = dexterityButtons.width;
                                        dexterityDecButton.fontSize = GameGUI.fontSize;
                                        dexterityDecButton.color = GameGUI.color;
                                        dexterityDecButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        dexterityDecButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        dexterityDecButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        dexterityDecButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    dexterityButtons.addControl(dexterityDecButton);
                                dexterityContainer.addControl(dexterityButtons);
                                let dexterityData = new BABYLON.GUI.StackPanel("dexterityData");
                                    dexterityData.height = dexterityContainer.height;
                                    dexterityData.width = String(dexterityContainer.widthInPixels - dexterityButtons.widthInPixels).concat("px");
                                    dexterityData.isVertical = true;
                                    let dexterityLabel = new BABYLON.GUI.TextBlock("dexterityLabel");
                                        dexterityLabel.height = String(dexterityContainer.heightInPixels / 4).concat("px");
                                        dexterityLabel.fontSize = GameGUI.fontSizeSmall;
                                        dexterityLabel.text = "Dexterity";
                                        dexterityLabel.color = GameGUI.color;
                                    dexterityData.addControl(dexterityLabel);
                                    let dexterityAbilityModifier = new BABYLON.GUI.TextBlock("dexterityAbilityModifier");
                                        dexterityAbilityModifier.height = String(dexterityContainer.heightInPixels / 2).concat("px");
                                        dexterityAbilityModifier.fontSize = GameGUI.fontSize;
                                        dexterityAbilityModifier.text = "0";
                                        dexterityAbilityModifier.color = GameGUI.color;
                                    dexterityData.addControl(dexterityAbilityModifier);
                                    let dexterityAbilityScore = new BABYLON.GUI.InputText("dexterityAbilityScore");
                                        dexterityAbilityScore.height = String(dexterityContainer.heightInPixels / 4).concat("px");
                                        dexterityAbilityScore.fontSize = GameGUI.fontSizeSmall;
                                        dexterityAbilityScore.text = "10";
                                        dexterityAbilityScore.color = GameGUI.color;
                                        dexterityAbilityScore.thickness = 0;
                                        dexterityAbilityScore.background = "";
                                        dexterityAbilityScore.isEnabled = false;
                                    dexterityData.addControl(dexterityAbilityScore);
                                dexterityContainer.addControl(dexterityData);
                            colARowAColA.addControl(dexterityContainer);
                            let constitutionContainer = new BABYLON.GUI.StackPanel("constitutionContainer");
                                constitutionContainer.height = String(colARowAColA.heightInPixels / 6).concat("px");
                                constitutionContainer.width = colARowAColA.width;
                                constitutionContainer.isVertical = false;
                                let constitutionButtons = new BABYLON.GUI.StackPanel("constitutionButtons");
                                    constitutionButtons.height = constitutionContainer.height;
                                    constitutionButtons.width = String(constitutionContainer.heightInPixels / 2).concat("px");
                                    constitutionButtons.isVeritcal = true;
                                    let constitutionIncButton = BABYLON.GUI.Button.CreateImageButton("constitutionInc", "+");
                                        constitutionIncButton.height = String(constitutionButtons.heightInPixels / 2).concat("px");
                                        constitutionIncButton.width = constitutionButtons.width;
                                        constitutionIncButton.fontSize = GameGUI.fontSize;
                                        constitutionIncButton.color = GameGUI.color;
                                        constitutionIncButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        constitutionIncButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        constitutionIncButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        constitutionIncButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    constitutionButtons.addControl(constitutionIncButton);
                                    let constitutionDecButton = BABYLON.GUI.Button.CreateImageButton("constitutionDec", "-");
                                        constitutionDecButton.height = String(constitutionButtons.heightInPixels / 2).concat("px");
                                        constitutionDecButton.width = constitutionButtons.width;
                                        constitutionDecButton.fontSize = GameGUI.fontSize;
                                        constitutionDecButton.color = GameGUI.color;
                                        constitutionDecButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        constitutionDecButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        constitutionDecButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        constitutionDecButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    constitutionButtons.addControl(constitutionDecButton);
                                constitutionContainer.addControl(constitutionButtons);
                                let constitutionData = new BABYLON.GUI.StackPanel("constitutionData");
                                    constitutionData.height = constitutionContainer.height;
                                    constitutionData.width = String(constitutionContainer.widthInPixels - constitutionButtons.widthInPixels).concat("px");
                                    constitutionData.isVertical = true;
                                    let constitutionLabel = new BABYLON.GUI.TextBlock("constitutionLabel");
                                        constitutionLabel.height = String(constitutionContainer.heightInPixels / 4).concat("px");
                                        constitutionLabel.fontSize = GameGUI.fontSizeSmall;
                                        constitutionLabel.text = "Constitution";
                                        constitutionLabel.color = GameGUI.color;
                                    constitutionData.addControl(constitutionLabel);
                                    let constitutionAbilityModifier = new BABYLON.GUI.TextBlock("constitutionAbilityModifier");
                                        constitutionAbilityModifier.height = String(constitutionContainer.heightInPixels / 2).concat("px");
                                        constitutionAbilityModifier.fontSize = GameGUI.fontSize;
                                        constitutionAbilityModifier.text = "0";
                                        constitutionAbilityModifier.color = GameGUI.color;
                                    constitutionData.addControl(constitutionAbilityModifier);
                                    let constitutionAbilityScore = new BABYLON.GUI.InputText("constitutionAbilityScore");
                                        constitutionAbilityScore.height = String(constitutionContainer.heightInPixels / 4).concat("px");
                                        constitutionAbilityScore.fontSize = GameGUI.fontSizeSmall;
                                        constitutionAbilityScore.text = "10";
                                        constitutionAbilityScore.color = GameGUI.color;
                                        constitutionAbilityScore.thickness = 0;
                                        constitutionAbilityScore.background = "";
                                        constitutionAbilityScore.isEnabled = false;
                                    constitutionData.addControl(constitutionAbilityScore);
                                constitutionContainer.addControl(constitutionData);
                            colARowAColA.addControl(constitutionContainer);
                            let intelligenceContainer = new BABYLON.GUI.StackPanel("intelligenceContainer");
                                intelligenceContainer.height = String(colARowAColA.heightInPixels / 6).concat("px");
                                intelligenceContainer.width = colARowAColA.width;
                                intelligenceContainer.isVertical = false;
                                let intelligenceButtons = new BABYLON.GUI.StackPanel("intelligenceButtons");
                                    intelligenceButtons.height = intelligenceContainer.height;
                                    intelligenceButtons.width = String(intelligenceContainer.heightInPixels / 2).concat("px");
                                    intelligenceButtons.isVeritcal = true;
                                    let intelligenceIncButton = BABYLON.GUI.Button.CreateImageButton("intelligenceInc", "+");
                                        intelligenceIncButton.height = String(intelligenceButtons.heightInPixels / 2).concat("px");
                                        intelligenceIncButton.width = intelligenceButtons.width;
                                        intelligenceIncButton.fontSize = GameGUI.fontSize;
                                        intelligenceIncButton.color = GameGUI.color;
                                        intelligenceIncButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        intelligenceIncButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        intelligenceIncButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        intelligenceIncButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    intelligenceButtons.addControl(intelligenceIncButton);
                                    let intelligenceDecButton = BABYLON.GUI.Button.CreateImageButton("intelligenceDec", "-");
                                        intelligenceDecButton.height = String(intelligenceButtons.heightInPixels / 2).concat("px");
                                        intelligenceDecButton.width = intelligenceButtons.width;
                                        intelligenceDecButton.fontSize = GameGUI.fontSize;
                                        intelligenceDecButton.color = GameGUI.color;
                                        intelligenceDecButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        intelligenceDecButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        intelligenceDecButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        intelligenceDecButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    intelligenceButtons.addControl(intelligenceDecButton);
                                intelligenceContainer.addControl(intelligenceButtons);
                                let intelligenceData = new BABYLON.GUI.StackPanel("intelligenceData");
                                    intelligenceData.height = intelligenceContainer.height;
                                    intelligenceData.width = String(intelligenceContainer.widthInPixels - intelligenceButtons.widthInPixels).concat("px");
                                    intelligenceData.isVertical = true;
                                    let intelligenceLabel = new BABYLON.GUI.TextBlock("intelligenceLabel");
                                        intelligenceLabel.height = String(intelligenceContainer.heightInPixels / 4).concat("px");
                                        intelligenceLabel.fontSize = GameGUI.fontSizeSmall;
                                        intelligenceLabel.text = "Intelligence";
                                        intelligenceLabel.color = GameGUI.color;
                                    intelligenceData.addControl(intelligenceLabel);
                                    let intelligenceAbilityModifier = new BABYLON.GUI.TextBlock("intelligenceAbilityModifier");
                                        intelligenceAbilityModifier.height = String(intelligenceContainer.heightInPixels / 2).concat("px");
                                        intelligenceAbilityModifier.fontSize = GameGUI.fontSize;
                                        intelligenceAbilityModifier.text = "0";
                                        intelligenceAbilityModifier.color = GameGUI.color;
                                    intelligenceData.addControl(intelligenceAbilityModifier);
                                    let intelligenceAbilityScore = new BABYLON.GUI.InputText("intelligenceAbilityScore");
                                        intelligenceAbilityScore.height = String(intelligenceContainer.heightInPixels / 4).concat("px");
                                        intelligenceAbilityScore.fontSize = GameGUI.fontSizeSmall;
                                        intelligenceAbilityScore.text = "10";
                                        intelligenceAbilityScore.color = GameGUI.color;
                                        intelligenceAbilityScore.thickness = 0;
                                        intelligenceAbilityScore.background = "";
                                        intelligenceAbilityScore.isEnabled = false;
                                    intelligenceData.addControl(intelligenceAbilityScore);
                                intelligenceContainer.addControl(intelligenceData);
                            colARowAColA.addControl(intelligenceContainer);
                            let wisdomContainer = new BABYLON.GUI.StackPanel("wisdomContainer");
                                wisdomContainer.height = String(colARowAColA.heightInPixels / 6).concat("px");
                                wisdomContainer.width = colARowAColA.width;
                                wisdomContainer.isVertical = false;
                                let wisdomButtons = new BABYLON.GUI.StackPanel("wisdomButtons");
                                    wisdomButtons.height = wisdomContainer.height;
                                    wisdomButtons.width = String(wisdomContainer.heightInPixels / 2).concat("px");
                                    wisdomButtons.isVeritcal = true;
                                    let wisdomIncButton = BABYLON.GUI.Button.CreateImageButton("wisdomInc", "+");
                                        wisdomIncButton.height = String(wisdomButtons.heightInPixels / 2).concat("px");
                                        wisdomIncButton.width = wisdomButtons.width;
                                        wisdomIncButton.fontSize = GameGUI.fontSize;
                                        wisdomIncButton.color = GameGUI.color;
                                        wisdomIncButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        wisdomIncButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        wisdomIncButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        wisdomIncButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    wisdomButtons.addControl(wisdomIncButton);
                                    let wisdomDecButton = BABYLON.GUI.Button.CreateImageButton("wisdomDec", "-");
                                        wisdomDecButton.height = String(wisdomButtons.heightInPixels / 2).concat("px");
                                        wisdomDecButton.width = wisdomButtons.width;
                                        wisdomDecButton.fontSize = GameGUI.fontSize;
                                        wisdomDecButton.color = GameGUI.color;
                                        wisdomDecButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        wisdomDecButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        wisdomDecButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        wisdomDecButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    wisdomButtons.addControl(wisdomDecButton);
                                wisdomContainer.addControl(wisdomButtons);
                                let wisdomData = new BABYLON.GUI.StackPanel("wisdomData");
                                    wisdomData.height = wisdomContainer.height;
                                    wisdomData.width = String(wisdomContainer.widthInPixels - wisdomButtons.widthInPixels).concat("px");
                                    wisdomData.isVertical = true;
                                    let wisdomLabel = new BABYLON.GUI.TextBlock("wisdomLabel");
                                        wisdomLabel.height = String(wisdomContainer.heightInPixels / 4).concat("px");
                                        wisdomLabel.fontSize = GameGUI.fontSizeSmall;
                                        wisdomLabel.text = "Wisdom";
                                        wisdomLabel.color = GameGUI.color;
                                    wisdomData.addControl(wisdomLabel);
                                    let wisdomAbilityModifier = new BABYLON.GUI.TextBlock("wisdomAbilityModifier");
                                        wisdomAbilityModifier.height = String(wisdomContainer.heightInPixels / 2).concat("px");
                                        wisdomAbilityModifier.fontSize = GameGUI.fontSize;
                                        wisdomAbilityModifier.text = "0";
                                        wisdomAbilityModifier.color = GameGUI.color;
                                    wisdomData.addControl(wisdomAbilityModifier);
                                    let wisdomAbilityScore = new BABYLON.GUI.InputText("wisdomAbilityScore");
                                        wisdomAbilityScore.height = String(wisdomContainer.heightInPixels / 4).concat("px");
                                        wisdomAbilityScore.fontSize = GameGUI.fontSizeSmall;
                                        wisdomAbilityScore.text = "10";
                                        wisdomAbilityScore.color = GameGUI.color;
                                        wisdomAbilityScore.thickness = 0;
                                        wisdomAbilityScore.background = "";
                                        wisdomAbilityScore.isEnabled = false;
                                    wisdomData.addControl(wisdomAbilityScore);
                                wisdomContainer.addControl(wisdomData);
                            colARowAColA.addControl(wisdomContainer);
                            let charismaContainer = new BABYLON.GUI.StackPanel("charismaContainer");
                                charismaContainer.height = String(colARowAColA.heightInPixels / 6).concat("px");
                                charismaContainer.width = colARowAColA.width;
                                charismaContainer.isVertical = false;
                                let charismaButtons = new BABYLON.GUI.StackPanel("charismaButtons");
                                    charismaButtons.height = charismaContainer.height;
                                    charismaButtons.width = String(charismaContainer.heightInPixels / 2).concat("px");
                                    charismaButtons.isVeritcal = true;
                                    let charismaIncButton = BABYLON.GUI.Button.CreateImageButton("charismaInc", "+");
                                        charismaIncButton.height = String(charismaButtons.heightInPixels / 2).concat("px");
                                        charismaIncButton.width = charismaButtons.width;
                                        charismaIncButton.fontSize = GameGUI.fontSize;
                                        charismaIncButton.color = GameGUI.color;
                                        charismaIncButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        charismaIncButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        charismaIncButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        charismaIncButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    charismaButtons.addControl(charismaIncButton);
                                    let charismaDecButton = BABYLON.GUI.Button.CreateImageButton("charismaDec", "-");
                                        charismaDecButton.height = String(charismaButtons.heightInPixels / 2).concat("px");
                                        charismaDecButton.width = charismaButtons.width;
                                        charismaDecButton.fontSize = GameGUI.fontSize;
                                        charismaDecButton.color = GameGUI.color;
                                        charismaDecButton.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        charismaDecButton.textVerticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                        charismaDecButton.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
                                        charismaDecButton.verticalAlignment = BABYLON.GUI.Control.VERTICAL_ALIGNMENT_CENTER;
                                    charismaButtons.addControl(charismaDecButton);
                                charismaContainer.addControl(charismaButtons);
                                let charismaData = new BABYLON.GUI.StackPanel("charismaData");
                                    charismaData.height = charismaContainer.height;
                                    charismaData.width = String(charismaContainer.widthInPixels - charismaButtons.widthInPixels).concat("px");
                                    charismaData.isVertical = true;
                                    let charismaLabel = new BABYLON.GUI.TextBlock("charismaLabel");
                                        charismaLabel.height = String(charismaContainer.heightInPixels / 4).concat("px");
                                        charismaLabel.fontSize = GameGUI.fontSizeSmall;
                                        charismaLabel.text = "Charisma";
                                        charismaLabel.color = GameGUI.color;
                                    charismaData.addControl(charismaLabel);
                                    let charismaAbilityModifier = new BABYLON.GUI.TextBlock("charismaAbilityModifier");
                                        charismaAbilityModifier.height = String(charismaContainer.heightInPixels / 2).concat("px");
                                        charismaAbilityModifier.fontSize = GameGUI.fontSize;
                                        charismaAbilityModifier.text = "0";
                                        charismaAbilityModifier.color = GameGUI.color;
                                    charismaData.addControl(charismaAbilityModifier);
                                    let charismaAbilityScore = new BABYLON.GUI.InputText("charismaAbilityScore");
                                        charismaAbilityScore.height = String(charismaContainer.heightInPixels / 4).concat("px");
                                        charismaAbilityScore.fontSize = GameGUI.fontSizeSmall;
                                        charismaAbilityScore.text = "10";
                                        charismaAbilityScore.color = GameGUI.color;
                                        charismaAbilityScore.thickness = 0;
                                        charismaAbilityScore.background = "";
                                        charismaAbilityScore.isEnabled = false;
                                    charismaData.addControl(charismaAbilityScore);
                                charismaContainer.addControl(charismaData);
                            colARowAColA.addControl(charismaContainer);
                        colARowA.addControl(colARowAColA);
                        let colARowAColB = new BABYLON.GUI.StackPanel("colAColB");
                            colARowAColB.height = colARowA.height;
                            colARowAColB.width = String(colARowA.widthInPixels / 2).concat("px");
                            colARowAColB.isVertical = true;
                            let inspirationContainer = new BABYLON.GUI.StackPanel("inspirationContainer");
                                inspirationContainer.height = String(colARowAColB.heightInPixels / 12).concat("px");
                                inspirationContainer.width = colARowAColB.width;
                                inspirationContainer.isVertical = false;
                                let inspirationScore = new BABYLON.GUI.TextBlock("inspirationScore");
                                    inspirationScore.height = inspirationContainer.height;
                                    inspirationScore.width = inspirationScore.height;
                                    inspirationScore.fontSize = GameGUI.fontSize;
                                    inspirationScore.text = "0";
                                    inspirationScore.color = GameGUI.color;
                                inspirationContainer.addControl(inspirationScore);
                                let inspirationLabel = new BABYLON.GUI.TextBlock("inspirationLabel");
                                    inspirationLabel.height = inspirationContainer.height;
                                    inspirationLabel.width = String(inspirationContainer.widthInPixels - inspirationScore.widthInPixels).concat("px");
                                    inspirationLabel.fontSize = GameGUI.fontSizeSmall;
                                    inspirationLabel.text = "Inspiration";
                                    inspirationLabel.color = GameGUI.color;
                                inspirationContainer.addControl(inspirationLabel);
                            colARowAColB.addControl(inspirationContainer);
                            let proficiencyBonusContainer = new BABYLON.GUI.StackPanel("proficiencyBonusContainer");
                                proficiencyBonusContainer.height = String(colARowAColB.heightInPixels / 12).concat("px");
                                proficiencyBonusContainer.width = colARowAColB.width;
                                proficiencyBonusContainer.isVertical = false;
                                let proficiencyBonusScore = new BABYLON.GUI.TextBlock("proficiencyBonusScore");
                                    proficiencyBonusScore.height = proficiencyBonusContainer.height;
                                    proficiencyBonusScore.width = proficiencyBonusScore.height;
                                    proficiencyBonusScore.fontSize = GameGUI.fontSize;
                                    proficiencyBonusScore.text = "0";
                                    proficiencyBonusScore.color = GameGUI.color;
                                proficiencyBonusContainer.addControl(proficiencyBonusScore);
                                let proficiencyBonusLabel = new BABYLON.GUI.TextBlock("proficiencyBonusLabel");
                                    proficiencyBonusLabel.height = proficiencyBonusContainer.height;
                                    proficiencyBonusLabel.width = String(proficiencyBonusContainer.widthInPixels - proficiencyBonusScore.widthInPixels).concat("px");
                                    proficiencyBonusLabel.fontSize = GameGUI.fontSizeSmall;
                                    proficiencyBonusLabel.text = "Proficiency Bonus";
                                    proficiencyBonusLabel.color = GameGUI.color;
                                proficiencyBonusContainer.addControl(proficiencyBonusLabel);
                            colARowAColB.addControl(proficiencyBonusContainer);
                            let savingThrowContainer = new BABYLON.GUI.StackPanel("savingThrowContainer");
                            colARowAColB.addControl(savingThrowContainer);
                        colARowA.addControl(colARowAColB);
                    colA.addControl(colARowA);
                    let colARowB = new BABYLON.GUI.StackPanel("colARowB");
                        colARowB.height = String((colA.heightInPixels / 7) * 0.5).concat("px");
                        colARowB.width = colA.width;
                        colARowB.isVertical = false;
                        let passiveWisdomScore = new BABYLON.GUI.TextBlock("passiveWisdomScore");
                            passiveWisdomScore.height = colARowB.height;
                            passiveWisdomScore.width = passiveWisdomScore.height;
                            passiveWisdomScore.fontSize = GameGUI.fontSize;
                            passiveWisdomScore.text = "0";
                            passiveWisdomScore.color = GameGUI.color;
                        colARowB.addControl(passiveWisdomScore);
                        let passiveWisdomLabel = new BABYLON.GUI.TextBlock("passiveWisdomLabel");
                            passiveWisdomLabel.height = colARowB.height;
                            passiveWisdomLabel.width = String(colARowB.widthInPixels - passiveWisdomScore.widthInPixels).concat("px");
                            passiveWisdomLabel.fontSize = GameGUI.fontSizeSmall;
                            passiveWisdomLabel.text = "Passive Wisdom (Perception)";
                            passiveWisdomLabel.color = GameGUI.color;
                        colARowB.addControl(passiveWisdomLabel);
                    colA.addControl(colARowB);
                    let colARowC = new BABYLON.GUI.StackPanel("colARowC");
                        colARowC.height = String((colA.heightInPixels / 7) * 2.5).concat("px");
                        colARowC.width = colA.width;
                        colARowC.isVertical = false;
                    colA.addControl(colARowC);
                body.addControl(colA);
                let colB = new BABYLON.GUI.StackPanel("colB");
                    colB.height = body.height;
                    colB.width = String(body.widthInPixels / 3).concat("px");
                    colB.isVertical = true;
                body.addControl(colB);
                let colC = new BABYLON.GUI.StackPanel("colC");
                    colC.height = body.height;
                    colC.width = String(body.widthInPixels / 3).concat("px");
                    colC.isVertical = true;
                body.addControl(colC);
            controller.addControl(body);
        CharacterStatsGUI.controller = controller;
        CharacterStatsGUI.header = header;
        CharacterStatsGUI.nameContainer = hNameContainer;
        CharacterStatsGUI.nameField = hNCField;
        CharacterStatsGUI.nameLabel = hNCLabel;
        CharacterStatsGUI.infoContainer = hInfoContainer;
        CharacterStatsGUI.infoTop = hICTop;
        CharacterStatsGUI.classContainer = hICTClassContainer;
        CharacterStatsGUI.classField = hICTCCText;
        CharacterStatsGUI.classLabel = hICTCCLabel;
        CharacterStatsGUI.backgroundContainer = hICTBGgContainer;
        CharacterStatsGUI.backgroundField = hICTBGCText;
        CharacterStatsGUI.backgroundLabel = hICTBGCLabel;
        CharacterStatsGUI.accountContainer = hICTAccNameContainer;
        CharacterStatsGUI.accountField = hICTANCText;
        CharacterStatsGUI.accountLabel = hICTANCLabel;
        CharacterStatsGUI.infoBottom = hICBot;
        CharacterStatsGUI.raceContainer = hICBRaceContainer;
        CharacterStatsGUI.raceField = hICBRCText;
        CharacterStatsGUI.raceLabel = hICBRCLabel;
        CharacterStatsGUI.alignmentContainer = hICBAlignmentContainer;
        CharacterStatsGUI.alignmentField = hICBACText;
        CharacterStatsGUI.alignmentLabel = hICBACLabel;
        CharacterStatsGUI.xpContainer = hICBXPContainer;
        CharacterStatsGUI.xpField = hICBXPCText;
        CharacterStatsGUI.xpLabel = hICBXPCLabel;
        CharacterStatsGUI.body = body;
        CharacterStatsGUI.colA = colA;
        CharacterStatsGUI.colARowA = colARowA;
        CharacterStatsGUI.colARowAColA = colARowAColA;
        CharacterStatsGUI.strengthContainer = strengthContainer;
        CharacterStatsGUI.strengthButtons = strengthButtons;
        CharacterStatsGUI.strengthIncButton = strengthIncButton;
        CharacterStatsGUI.strengthDecButton = strengthDecButton;
        CharacterStatsGUI.strengthData = strengthData;
        CharacterStatsGUI.strengthLabel = strengthLabel;
        CharacterStatsGUI.strengthAbilityModifier = strengthAbilityModifier;
        CharacterStatsGUI.strengthAbilityField = strengthAbilityScore;
        CharacterStatsGUI.dexterityContainer = dexterityContainer;
        CharacterStatsGUI.dexterityButtons = dexterityButtons;
        CharacterStatsGUI.dexterityIncButton = dexterityIncButton;
        CharacterStatsGUI.dexterityDecButton = dexterityDecButton;
        CharacterStatsGUI.dexterityData = dexterityData;
        CharacterStatsGUI.dexterityLabel = dexterityLabel;
        CharacterStatsGUI.dexterityAbilityModifier = dexterityAbilityModifier;
        CharacterStatsGUI.dexterityAbilityField = dexterityAbilityScore;
        CharacterStatsGUI.constitutionContainer = constitutionContainer;
        CharacterStatsGUI.constitutionButtons = constitutionButtons;
        CharacterStatsGUI.constitutionIncButton = constitutionIncButton;
        CharacterStatsGUI.constitutionDecButton = constitutionDecButton;
        CharacterStatsGUI.constitutionData = constitutionData;
        CharacterStatsGUI.constitutionLabel = constitutionLabel;
        CharacterStatsGUI.constitutionAbilityModifier = constitutionAbilityModifier;
        CharacterStatsGUI.constitutionAbilityField = constitutionAbilityScore;
        CharacterStatsGUI.intelligenceContainer = intelligenceContainer;
        CharacterStatsGUI.intelligenceButtons = intelligenceButtons;
        CharacterStatsGUI.intelligenceIncButton = intelligenceIncButton;
        CharacterStatsGUI.intelligenceDecButton = intelligenceDecButton;
        CharacterStatsGUI.intelligenceData = intelligenceData;
        CharacterStatsGUI.intelligenceLabel = intelligenceLabel;
        CharacterStatsGUI.intelligenceAbilityModifier = intelligenceAbilityModifier;
        CharacterStatsGUI.intelligenceAbilityField = intelligenceAbilityScore;
        CharacterStatsGUI.wisdomContainer = wisdomContainer;
        CharacterStatsGUI.wisdomButtons = wisdomButtons;
        CharacterStatsGUI.wisdomIncButton = wisdomIncButton;
        CharacterStatsGUI.wisdomDecButton = wisdomDecButton;
        CharacterStatsGUI.wisdomData = wisdomData;
        CharacterStatsGUI.wisdomLabel = wisdomLabel;
        CharacterStatsGUI.wisdomAbilityModifier = wisdomAbilityModifier;
        CharacterStatsGUI.wisdomAbilityField = wisdomAbilityScore;
        CharacterStatsGUI.charismaContainer = charismaContainer;
        CharacterStatsGUI.charismaButtons = charismaButtons;
        CharacterStatsGUI.charismaIncButton = charismaIncButton;
        CharacterStatsGUI.charismaDecButton = charismaDecButton;
        CharacterStatsGUI.charismaData = charismaData;
        CharacterStatsGUI.charismaLabel = charismaLabel;
        CharacterStatsGUI.charismaAbilityModifier = charismaAbilityModifier;
        CharacterStatsGUI.charismaAbilityField = charismaAbilityScore;
        CharacterStatsGUI.colARowAColB = colARowAColB;
        CharacterStatsGUI.inspirationContainer = inspirationContainer;
        CharacterStatsGUI.inspirationField = inspirationScore;
        CharacterStatsGUI.inspirationLabel = inspirationLabel;
        CharacterStatsGUI.proficiencyBonusContainer = proficiencyBonusContainer;
        CharacterStatsGUI.proficiencyBonusField = proficiencyBonusScore;
        CharacterStatsGUI.proficiencyBonusLabel = proficiencyBonusLabel;
        CharacterStatsGUI.colARowB = colARowB;
        CharacterStatsGUI.passiveWisdomField = passiveWisdomScore;
        CharacterStatsGUI.passiveWisdomLabel = passiveWisdomLabel;
        CharacterStatsGUI.colARowC = colARowC;
        CharacterStatsGUI.colB = colB;
        CharacterStatsGUI.colC = colC;
        CharacterStatsGUI.initialized = true;
        return controller;
    }
    static getController() {
        return CharacterStatsGUI.controller;
    }
    static isVisible() {
        return CharacterStatsGUI.controller.isVisible;
    }
    static show() {
        CharacterStatsGUI.controller.isVisible = true;
    }
    static hide() {
        CharacterStatsGUI.controller.isVisible = false;
    }
    static updateWith(creatureEntity = Game.player) {
        CharacterStatsGUI.nameField.text = creatureEntity.getName();
        CharacterStatsGUI.classField.text = creatureEntity.getClass().getName();
        //CharacterStatsGUI.backgroundField.text = creatureEntity.get();
        //CharacterStatsGUI.accountNameField.text = creatureEntity.get();
        CharacterStatsGUI.raceField.text = CreatureSubTypeEnum.properties[creatureEntity.getCreatureSubType()].name;
        //CharacterStatsGUI.alignmentField.text = creatureEntity.get();
        CharacterStatsGUI.xpField.text = String(creatureEntity.getXP());
        let number = Game.calculateAbilityModifier(creatureEntity.getStrength());
        CharacterStatsGUI.strengthAbilityModifier.text = String((number > 0 ? "+" : "") + number);
        CharacterStatsGUI.strengthAbilityField.text = String(creatureEntity.getStrength());
        number = Game.calculateAbilityModifier(creatureEntity.getDexterity());
        CharacterStatsGUI.dexterityAbilityModifier.text = String((number > 0 ? "+" : "") + number);
        CharacterStatsGUI.dexterityAbilityField.text = String(creatureEntity.getDexterity())
        number = Game.calculateAbilityModifier(creatureEntity.getConstitution());
        CharacterStatsGUI.constitutionAbilityModifier.text = String((number > 0 ? "+" : "") + number);
        CharacterStatsGUI.constitutionAbilityField.text = String(creatureEntity.getConstitution());
        number = Game.calculateAbilityModifier(creatureEntity.getIntelligence());
        CharacterStatsGUI.intelligenceAbilityModifier.text = String((number > 0 ? "+" : "") + number);
        CharacterStatsGUI.intelligenceAbilityField.text = String(creatureEntity.getIntelligence());
        number = Game.calculateAbilityModifier(creatureEntity.getWisdom());
        CharacterStatsGUI.wisdomAbilityModifier.text = String((number > 0 ? "+" : "") + number);
        CharacterStatsGUI.wisdomAbilityField.text = String(creatureEntity.getWisdom());
        number = Game.calculateAbilityModifier(creatureEntity.getCharisma());
        CharacterStatsGUI.charismaAbilityModifier.text = String((number > 0 ? "+" : "") + number);
        CharacterStatsGUI.charismaAbilityField.text = String(creatureEntity.getCharisma());
    }
}